global using Android.App;
global using Android.Content;
global using Android.Views;
global using Android.Views.InputMethods;
global using View = Android.Views.View;
global using Android.Gms.Common.Apis;
global using Android.Locations;
global using Android.OS;
global using Android.Util;
global using Microsoft.Maui.Platform;
global using Android.Webkit;
global using Android.Widget;
global using Plugin.Maui.Biometric;
global using Bitmap = Android.Graphics.Bitmap;
global using BitmapFactory = Android.Graphics.BitmapFactory;
global using FileProvider = AndroidX.Core.Content.FileProvider;
global using Platform = Microsoft.Maui.ApplicationModel.Platform;
global using Size = Microsoft.Maui.Graphics.Size;
global using Typeface = Android.Graphics.Typeface;