//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAUIEssentials.AppResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppColorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AppColorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAUIEssentials.AppResources.AppColorResources", typeof(AppColorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF5C39.
        /// </summary>
        public static string badgeColor {
            get {
                return ResourceManager.GetString("badgeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #000000.
        /// </summary>
        public static string black {
            get {
                return ResourceManager.GetString("black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4D000000.
        /// </summary>
        public static string black30Opacity {
            get {
                return ResourceManager.GetString("black30Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #66000000.
        /// </summary>
        public static string black38Opacity {
            get {
                return ResourceManager.GetString("black38Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #80000000.
        /// </summary>
        public static string black50Opacity {
            get {
                return ResourceManager.GetString("black50Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #8C000000.
        /// </summary>
        public static string black54Opacity {
            get {
                return ResourceManager.GetString("black54Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #99000000.
        /// </summary>
        public static string black60Opacity {
            get {
                return ResourceManager.GetString("black60Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E6000000.
        /// </summary>
        public static string black87Opacity {
            get {
                return ResourceManager.GetString("black87Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #333333.
        /// </summary>
        public static string blackTextColor {
            get {
                return ResourceManager.GetString("blackTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00a0df.
        /// </summary>
        public static string blueColor {
            get {
                return ResourceManager.GetString("blueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #6600a0df.
        /// </summary>
        public static string blueColorOpacity40 {
            get {
                return ResourceManager.GetString("blueColorOpacity40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #0F00a0df.
        /// </summary>
        public static string bluecolorOpacity5 {
            get {
                return ResourceManager.GetString("bluecolorOpacity5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ECEFF1.
        /// </summary>
        public static string blueGray50 {
            get {
                return ResourceManager.GetString("blueGray50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #02C7C6.
        /// </summary>
        public static string bookingImageColor {
            get {
                return ResourceManager.GetString("bookingImageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #7b7e7f.
        /// </summary>
        public static string borderColor {
            get {
                return ResourceManager.GetString("borderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00b4ea.
        /// </summary>
        public static string brightSkyBlue {
            get {
                return ResourceManager.GetString("brightSkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #EFF8FB.
        /// </summary>
        public static string brightSkyBlue30 {
            get {
                return ResourceManager.GetString("brightSkyBlue30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1A000000.
        /// </summary>
        public static string clickColorBlack {
            get {
                return ResourceManager.GetString("clickColorBlack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #52FFFFFF.
        /// </summary>
        public static string clickColorWhite {
            get {
                return ResourceManager.GetString("clickColorWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00B4EA.
        /// </summary>
        public static string cyanColor {
            get {
                return ResourceManager.GetString("cyanColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00c7c7.
        /// </summary>
        public static string cyanColorBookingConfirmation {
            get {
                return ResourceManager.GetString("cyanColorBookingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #66314137.
        /// </summary>
        public static string darkgrayMediumOpacity {
            get {
                return ResourceManager.GetString("darkgrayMediumOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #646464.
        /// </summary>
        public static string darkGrayTextColor {
            get {
                return ResourceManager.GetString("darkGrayTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ff5d39.
        /// </summary>
        public static string darkOrangeColor {
            get {
                return ResourceManager.GetString("darkOrangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #373737.
        /// </summary>
        public static string eclipse {
            get {
                return ResourceManager.GetString("eclipse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4D333333.
        /// </summary>
        public static string Gray30Opacity {
            get {
                return ResourceManager.GetString("Gray30Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #99333333.
        /// </summary>
        public static string Gray90Opacity {
            get {
                return ResourceManager.GetString("Gray90Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e8e8e8.
        /// </summary>
        public static string Gray91 {
            get {
                return ResourceManager.GetString("Gray91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #b2b2b2.
        /// </summary>
        public static string grayColor {
            get {
                return ResourceManager.GetString("grayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #40E8E8E8.
        /// </summary>
        public static string grayColorOpacity25 {
            get {
                return ResourceManager.GetString("grayColorOpacity25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ccb2b2b2.
        /// </summary>
        public static string grayColorOpacity80 {
            get {
                return ResourceManager.GetString("grayColorOpacity80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #535353.
        /// </summary>
        public static string grayHeaderColor {
            get {
                return ResourceManager.GetString("grayHeaderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #808080.
        /// </summary>
        public static string grayTextColor {
            get {
                return ResourceManager.GetString("grayTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #39b54a.
        /// </summary>
        public static string greenColor {
            get {
                return ResourceManager.GetString("greenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1739b54a.
        /// </summary>
        public static string greenColorOpacity9 {
            get {
                return ResourceManager.GetString("greenColorOpacity9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00c1d1.
        /// </summary>
        public static string headerbluecolor {
            get {
                return ResourceManager.GetString("headerbluecolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #b2b2b2.
        /// </summary>
        public static string lightBorderColor {
            get {
                return ResourceManager.GetString("lightBorderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e8e8e8.
        /// </summary>
        public static string lightBorderColor2 {
            get {
                return ResourceManager.GetString("lightBorderColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #CCCCCC.
        /// </summary>
        public static string lightgray {
            get {
                return ResourceManager.GetString("lightgray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4De8e8e8.
        /// </summary>
        public static string LightGray30Opacity {
            get {
                return ResourceManager.GetString("LightGray30Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #99e8e8e8.
        /// </summary>
        public static string LightGray90Opacity {
            get {
                return ResourceManager.GetString("LightGray90Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #f2f2f2.
        /// </summary>
        public static string lightGrayColor {
            get {
                return ResourceManager.GetString("lightGrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #f0f0f0.
        /// </summary>
        public static string lightGrayColor0 {
            get {
                return ResourceManager.GetString("lightGrayColor0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #f7f7f7.
        /// </summary>
        public static string lightGrayColor7 {
            get {
                return ResourceManager.GetString("lightGrayColor7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #f9f9f9.
        /// </summary>
        public static string lightGrayColor9 {
            get {
                return ResourceManager.GetString("lightGrayColor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4D00ae42.
        /// </summary>
        public static string lightGreenColor9 {
            get {
                return ResourceManager.GetString("lightGreenColor9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FFDFE7.
        /// </summary>
        public static string lightRedColor {
            get {
                return ResourceManager.GetString("lightRedColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FDE0B1.
        /// </summary>
        public static string lightYellowColor {
            get {
                return ResourceManager.GetString("lightYellowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #33cdcd.
        /// </summary>
        public static string mediumTurquoise {
            get {
                return ResourceManager.GetString("mediumTurquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #f89203.
        /// </summary>
        public static string orangeColor {
            get {
                return ResourceManager.GetString("orangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #33f89203.
        /// </summary>
        public static string orangeColorOpacity20 {
            get {
                return ResourceManager.GetString("orangeColorOpacity20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #88000000.
        /// </summary>
        public static string overlay {
            get {
                return ResourceManager.GetString("overlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #4CD3D4.
        /// </summary>
        public static string PaymentSDKColor {
            get {
                return ResourceManager.GetString("PaymentSDKColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #40B8E7.
        /// </summary>
        public static string pictonBlueColor {
            get {
                return ResourceManager.GetString("pictonBlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1A40B8E7.
        /// </summary>
        public static string pictonBlueColorOpacity10 {
            get {
                return ResourceManager.GetString("pictonBlueColorOpacity10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #CC242424.
        /// </summary>
        public static string popupBgColor {
            get {
                return ResourceManager.GetString("popupBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00ae42.
        /// </summary>
        public static string PrimaryGreen {
            get {
                return ResourceManager.GetString("PrimaryGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #BF00ae42.
        /// </summary>
        public static string PrimaryGreen75Opacity {
            get {
                return ResourceManager.GetString("PrimaryGreen75Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #df0000.
        /// </summary>
        public static string redColor {
            get {
                return ResourceManager.GetString("redColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #e0e0e0.
        /// </summary>
        public static string shadowGray {
            get {
                return ResourceManager.GetString("shadowGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #40b8e7.
        /// </summary>
        public static string SkyBlue {
            get {
                return ResourceManager.GetString("SkyBlue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #8b8b8b.
        /// </summary>
        public static string SuvaGray {
            get {
                return ResourceManager.GetString("SuvaGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #A5A5A5.
        /// </summary>
        public static string switchOffThumb {
            get {
                return ResourceManager.GetString("switchOffThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #00FFFFFF.
        /// </summary>
        public static string Transparent {
            get {
                return ResourceManager.GetString("Transparent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #8cffffff.
        /// </summary>
        public static string white54Opacity {
            get {
                return ResourceManager.GetString("white54Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #99ffffff.
        /// </summary>
        public static string white60Opacity {
            get {
                return ResourceManager.GetString("white60Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E6ffffff.
        /// </summary>
        public static string white87facity {
            get {
                return ResourceManager.GetString("white87facity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #E6ffffff.
        /// </summary>
        public static string white87Opacity {
            get {
                return ResourceManager.GetString("white87Opacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #fbb13b.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #66fbb13b.
        /// </summary>
        public static string YellowColorOpacity40 {
            get {
                return ResourceManager.GetString("YellowColorOpacity40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #17fbb13b.
        /// </summary>
        public static string YellowColorOpacity9 {
            get {
                return ResourceManager.GetString("YellowColorOpacity9", resourceCulture);
            }
        }
    }
}
