//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAUIEssentials.AppResources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationResources
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public LocalizationResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAUIEssentials.AppResources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Take Now.
        /// </summary>
        public static string takeNow
        {
            get
            {
                return ResourceManager.GetString("takeNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose from gallery.
        /// </summary>
        public static string chooseFromGallery
        {
            get
            {
                return ResourceManager.GetString("chooseFromGallery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Document.
        /// </summary>
        public static string selectDocument
        {
            get
            {
                return ResourceManager.GetString("selectDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string selectFile
        {
            get
            {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload.
        /// </summary>
        public static string selectFileUpload
        {
            get
            {
                return ResourceManager.GetString("selectFileUpload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel
        {
            get
            {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string ok
        {
            get
            {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string search
        {
            get
            {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string retry
        {
            get
            {
                return ResourceManager.GetString("retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No internet connection!.
        /// </summary>
        public static string checkInternet
        {
            get
            {
                return ResourceManager.GetString("checkInternet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        public static string uploadFiles
        {
            get
            {
                return ResourceManager.GetString("uploadFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter postcode.
        /// </summary>
        public static string enterPostcode
        {
            get
            {
                return ResourceManager.GetString("enterPostcode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose an address.
        /// </summary>
        public static string chooseAddress
        {
            get
            {
                return ResourceManager.GetString("chooseAddress", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string pleaseWaitString
        {
            get
            {
                return ResourceManager.GetString("pleaseWaitString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current Plan.
        /// </summary>
        public static string currentPlan
        {
            get
            {
                return ResourceManager.GetString("currentPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Your Plan.
        /// </summary>
        public static string changeYourPlan
        {
            get
            {
                return ResourceManager.GetString("changeYourPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Switch To This Plan.
        /// </summary>
        public static string switchToThisPlan
        {
            get
            {
                return ResourceManager.GetString("switchToThisPlan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Your {0}-Day Trial.
        /// </summary>
        public static string startTrialString
        {
            get
            {
                return ResourceManager.GetString("startTrialString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string getStartedPayment
        {
            get
            {
                return ResourceManager.GetString("getStartedPayment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string noPlanForThisPeriod
        {
            get
            {
                return ResourceManager.GetString("noPlanForThisPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new card.
        /// </summary>
        public static string addNewCard
        {
            get
            {
                return ResourceManager.GetString("addNewCard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string expiryDate
        {
            get
            {
                return ResourceManager.GetString("expiryDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string cardNumber
        {
            get
            {
                return ResourceManager.GetString("cardNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Cards.
        /// </summary>
        public static string cards
        {
            get
            {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pay cash.
        /// </summary>
        public static string cashText
        {
            get
            {
                return ResourceManager.GetString("cashText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string applePay
        {
            get
            {
                return ResourceManager.GetString("applePay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google pay.
        /// </summary>
        public static string googlePay
        {
            get
            {
                return ResourceManager.GetString("googlePay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You&apos;ll enter you new card details in the next page.
        /// </summary>
        public static string NewCardDetail
        {
            get
            {
                return ResourceManager.GetString("NewCardDetail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string resourceBusyPeriod
        {
            get
            {
                return ResourceManager.GetString("resourceBusyPeriod", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not rated yet.
        /// </summary>
        public static string notRatedYet
        {
            get
            {
                return ResourceManager.GetString("notRatedYet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string km
        {
            get
            {
                return ResourceManager.GetString("km", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        public static string meter
        {
            get
            {
                return ResourceManager.GetString("meter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings Menu.
        /// </summary>
        public static string openSettings
        {
            get
            {
                return ResourceManager.GetString("openSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Permission Required.
        /// </summary>
        public static string permissionRequired
        {
            get
            {
                return ResourceManager.GetString("permissionRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Camera permission is necessary for the import. Would you like to open settings to grant it?.
        /// </summary>
        public static string permissionRequiredForCamera
        {
            get
            {
                return ResourceManager.GetString("permissionRequiredForCamera", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Read contact permission is necessary for the import. Would you like to open settings to grant it?.
        /// </summary>
        public static string permissionRequiredForImport
        {
            get
            {
                return ResourceManager.GetString("permissionRequiredForImport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show on map.
        /// </summary>
        public static string showOnMap
        {
            get
            {
                return ResourceManager.GetString("showOnMap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apple Maps.
        /// </summary>
        public static string appleMap
        {
            get
            {
                return ResourceManager.GetString("appleMap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Google Maps.
        /// </summary>
        public static string googleMap
        {
            get
            {
                return ResourceManager.GetString("googleMap", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        public static string pleaseWait
        {
            get
            {
                return ResourceManager.GetString("pleaseWait", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you would like to be able to find services close to you, please allow DORI app to access your location while using the app.
        /// </summary>
        public static string locationPermissionInfoMsg
        {
            get
            {
                return ResourceManager.GetString("locationPermissionInfoMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string allow
        {
            get
            {
                return ResourceManager.GetString("allow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enable multiple {0} for this {1}.
        /// </summary>
        public static string allowOptionMultiSelect
        {
            get
            {
                return ResourceManager.GetString("allowOptionMultiSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string hrsStr
        {
            get
            {
                return ResourceManager.GetString("hrsStr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string hrStr
        {
            get
            {
                return ResourceManager.GetString("hrStr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        public static string mins
        {
            get
            {
                return ResourceManager.GetString("mins", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email is not supported on this device.
        /// </summary>
        public static string emailNotSupport
        {
            get
            {
                return ResourceManager.GetString("emailNotSupport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan your faceprint.
        /// </summary>
        public static string scanYourFaceprint
        {
            get
            {
                return ResourceManager.GetString("scanYourFaceprint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scan your fingerprint.
        /// </summary>
        public static string scanYourFinger
        {
            get
            {
                return ResourceManager.GetString("scanYourFinger", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fingerprint.
        /// </summary>
        public static string fingerprint
        {
            get
            {
                return ResourceManager.GetString("fingerprint", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Face Id.
        /// </summary>
        public static string faceId
        {
            get
            {
                return ResourceManager.GetString("faceId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Touch ID for &quot;MAUIEssentials&quot;.
        /// </summary>
        public static string touchIdMAUIEssentials
        {
            get
            {
                return ResourceManager.GetString("touchIdMAUIEssentials", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome
        {
            get
            {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string login
        {
            get
            {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string email
        {
            get
            {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string password
        {
            get
            {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string enterPassword
        {
            get
            {
                return ResourceManager.GetString("enterPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string enterEmail
        {
            get
            {
                return ResourceManager.GetString("enterEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect email address.
        /// </summary>
        public static string validateEmail
        {
            get
            {
                return ResourceManager.GetString("validateEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email or Password is incorrect.
        /// </summary>
        public static string incorrectEmailPassword
        {
            get
            {
                return ResourceManager.GetString("incorrectEmailPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string postcode
        {
            get
            {
                return ResourceManager.GetString("postcode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sample Form.
        /// </summary>
        public static string sampleForm
        {
            get
            {
                return ResourceManager.GetString("sampleForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string firstName
        {
            get
            {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string lastName
        {
            get
            {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string notes
        {
            get
            {
                return ResourceManager.GetString("notes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string confirmPassword
        {
            get
            {
                return ResourceManager.GetString("confirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string designation
        {
            get
            {
                return ResourceManager.GetString("designation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string country
        {
            get
            {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string dateOfBirth
        {
            get
            {
                return ResourceManager.GetString("dateOfBirth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string gender
        {
            get
            {
                return ResourceManager.GetString("gender", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terms of Conditions.
        /// </summary>
        public static string termsOfConditions
        {
            get
            {
                return ResourceManager.GetString("termsOfConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Sample.
        /// </summary>
        public static string switchSample
        {
            get
            {
                return ResourceManager.GetString("switchSample", resourceCulture);
            }
        }
    }
}
