//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAUIEssentials.AppResources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAUIEssentials.AppResources.LocalizationResources", typeof(LocalizationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Take Now.
        /// </summary>
        internal static string takeNow
        {
            get
            {
                return ResourceManager.GetString("takeNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Choose from gallery.
        /// </summary>
        internal static string chooseFromGallery
        {
            get
            {
                return ResourceManager.GetString("chooseFromGallery", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Document.
        /// </summary>
        internal static string selectDocument
        {
            get
            {
                return ResourceManager.GetString("selectDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string selectFile
        {
            get
            {
                return ResourceManager.GetString("selectFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please select a file to upload.
        /// </summary>
        internal static string selectFileUpload
        {
            get
            {
                return ResourceManager.GetString("selectFileUpload", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel
        {
            get
            {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok
        {
            get
            {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string search
        {
            get
            {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string retry
        {
            get
            {
                return ResourceManager.GetString("retry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No internet connection!.
        /// </summary>
        internal static string checkInternet
        {
            get
            {
                return ResourceManager.GetString("checkInternet", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload Files.
        /// </summary>
        internal static string uploadFiles
        {
            get
            {
                return ResourceManager.GetString("uploadFiles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please enter postcode.
        /// </summary>
        internal static string enterPostcode
        {
            get
            {
                return ResourceManager.GetString("enterPostcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an address.
        /// </summary>
        internal static string chooseAddress {
            get {
                return ResourceManager.GetString("chooseAddress", resourceCulture);
            }
        }
    }
}
