global using System.Collections;
global using System.Collections.Specialized;
global using System.Runtime.CompilerServices;
global using MAUIEssentials.AppCode.Helpers;
global using System;
global using Microsoft.Maui;
global using Microsoft.Maui.Controls;
global using System.ComponentModel;
global using System.Windows.Input;
global using Microsoft.Maui.Controls.Maps;
global using Map = Microsoft.Maui.Controls.Maps.Map;
global using static System.Math;
global using CommunityToolkit.Maui.Behaviors;
global using System.Net;
global using System.Text;