global using Bumptech.Glide;
global using Bumptech.Glide.Load;
global using Bumptech.Glide.Load.Engine;
global using Bumptech.Glide.Request;
global using Bumptech.Glide.Request.Target;
global using Microsoft.Maui.Controls.Platform;
global using CustomImage = MAUIEssentials.AppCode.Controls.CaptchaImage;
global using Image = Microsoft.Maui.Controls.Image;
global using Google.Android.Material.BottomNavigation;
global using Microsoft.Maui.Controls.Platform.Compatibility;
global using AView = Android.Views.View;
global using Paint = Android.Graphics.Paint;
global using Path = Android.Graphics.Path;
global using Microsoft.Maui.Controls.Compatibility;
global using MAUIEssentials.Platforms.Android.Renderers;