global using Android.Text;
global using Android.Text.Style;
global using Android.Widget;
global using Org.Xml.Sax;
global using Android.Content;
global using Android.Content.Res;
global using Android.Graphics;
global using Android.Graphics.Drawables;
global using Android.OS;
global using Java.Net;
global using Android.Util;
global using MAUIEssentials.AppCode.Helpers;
global using Color = Android.Graphics.Color;